import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { errMsg } from "@/lib/session";
import { CompanyScope, RecordForm, type Field } from "./core";
import { PageHeader, Loading, ErrorState, Empty } from "./states";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import type { Database } from "@/integrations/supabase/types";

type Company=Database["public"]["Tables"]["companies"]["Row"];
type Store=Database["public"]["Tables"]["stores"]["Row"];
export function Companies(){const qc=useQueryClient();const [edit,setEdit]=useState<Partial<Company>|null>(null);const [busy,setBusy]=useState(false);const q=useQuery({queryKey:["companies-management"],queryFn:async()=>{const r=await supabase.from("companies").select("*").order("name");if(r.error)throw r.error;return r.data;}});
const fields:Field[]=[{key:"legal_name",label:"Razão social",required:true},{key:"name",label:"Nome fantasia",required:true},{key:"cnpj",label:"CNPJ"},{key:"contact_name",label:"Contato"},{key:"phone",label:"Telefone",type:"tel"},{key:"email",label:"Email",type:"email"},{key:"address",label:"Endereço"},{key:"city",label:"Cidade"},{key:"segment",label:"Segmento"}];
return <><PageHeader title="Empresas" actions={<Button onClick={()=>setEdit({})}>Criar empresa</Button>}/>{q.error?<ErrorState error={q.error} retry={()=>q.refetch()}/>:q.isLoading?<Loading/>:!q.data?.length?<Empty title="Nenhuma empresa"/>:<div className="space-y-3">{q.data.map(c=><article key={c.id} className="rounded-lg border bg-card p-5"><div className="flex flex-wrap justify-between gap-2"><h2 className="font-semibold">{c.name}</h2><Badge variant={c.active?"success":"muted"}>{c.active?"Ativa":"Inativa"}</Badge></div><p className="my-2 text-sm text-muted-foreground">{c.legal_name} · {c.cnpj} · {c.city}</p><div className="flex gap-2"><Button size="sm" variant="outline" onClick={()=>setEdit(c)}>Visualizar / editar</Button><Button size="sm" variant="outline" disabled={busy} onClick={async()=>{setBusy(true);try{const r=await supabase.from("companies").update({active:!c.active}).eq("id",c.id).select("id").single();if(r.error)throw r.error;await qc.invalidateQueries();toast.success("Status atualizado");}catch(e){toast.error(errMsg(e));}finally{setBusy(false);}}}>{c.active?"Inativar":"Ativar"}</Button></div></article>)}</div>}{edit&&<RecordForm title={edit.id?"Empresa":"Nova empresa"} fields={fields} initial={{...edit,legal_name:edit.legal_name||edit.name}} onClose={()=>setEdit(null)} onSave={async v=>{if((v["name"] ?? "").trim().length<2)throw Error("Informe o nome da empresa");if((v["cnpj"] ?? "")&&(v["cnpj"] ?? "").replace(/\D/g,"").length!==14)throw Error("CNPJ deve conter 14 dígitos");let id=edit.id;if(!id){const r=await supabase.rpc("create_company",{_name:(v["name"] ?? ""),_cnpj:(v["cnpj"] ?? ""),_city:(v["city"] ?? ""),_segment:(v["segment"] ?? "")});if(r.error)throw r.error;id=r.data;}const r=await supabase.from("companies").update({name:(v["name"] ?? ""),trade_name:(v["name"] ?? ""),legal_name:(v["legal_name"] ?? ""),cnpj:(v["cnpj"] ?? ""),contact_name:(v["contact_name"] ?? ""),phone:(v["phone"] ?? ""),email:(v["email"] ?? ""),address:(v["address"] ?? ""),city:(v["city"] ?? ""),segment:(v["segment"] ?? "")}).eq("id",id).select("id").single();if(r.error)throw r.error;await qc.invalidateQueries();toast.success("Empresa salva");}}/>}</>;
}
export function Stores(){return <CompanyScope>{c=><StoreList companyId={c.id}/>}</CompanyScope>;}
function StoreList({companyId}:{companyId:string}){const qc=useQueryClient();const [edit,setEdit]=useState<Partial<Store>|null>(null);const [busy,setBusy]=useState(false);const q=useQuery({queryKey:["stores-management",companyId],queryFn:async()=>{const r=await supabase.from("stores").select("*").eq("company_id",companyId).order("name");if(r.error)throw r.error;return r.data;}});const fields:Field[]=[{key:"name",label:"Nome",required:true},{key:"address",label:"Endereço",required:true},{key:"city",label:"Cidade",required:true},{key:"region",label:"Região"},{key:"contact_name",label:"Responsável"},{key:"phone",label:"Telefone",type:"tel"},{key:"hours",label:"Horário"}];
return <><PageHeader title="Lojas" actions={<Button onClick={()=>setEdit({})}>Criar loja</Button>}/>{q.error?<ErrorState error={q.error}/>:q.isLoading?<Loading/>:!q.data?.length?<Empty title="Nenhuma loja"/>:<div className="space-y-3">{q.data.map(s=><article key={s.id} className="rounded-lg border bg-card p-5"><h2 className="font-semibold">{s.name} <Badge variant="muted">{s.active?"Ativa":"Inativa"}</Badge></h2><p className="my-2 text-sm text-muted-foreground">{s.address} · {s.city} · {s.region}</p><div className="flex gap-2"><Button size="sm" variant="outline" onClick={()=>setEdit(s)}>Visualizar / editar</Button><Button size="sm" variant="outline" disabled={busy} onClick={async()=>{setBusy(true);try{const r=await supabase.from("stores").update({active:!s.active}).eq("id",s.id).select("id").single();if(r.error)throw r.error;await qc.invalidateQueries();toast.success("Status atualizado");}catch(e){toast.error(errMsg(e));}finally{setBusy(false);}}}>{s.active?"Inativar":"Ativar"}</Button></div></article>)}</div>}{edit&&<RecordForm title={edit.id?"Loja":"Nova loja"} fields={fields} initial={edit} onClose={()=>setEdit(null)} onSave={async v=>{const data={name:(v["name"] ?? ""),address:(v["address"] ?? ""),city:(v["city"] ?? ""),region:(v["region"] ?? ""),contact_name:(v["contact_name"] ?? ""),phone:(v["phone"] ?? ""),hours:(v["hours"] ?? "")};const r=edit.id?await supabase.from("stores").update(data).eq("id",edit.id).select("id").single():await supabase.from("stores").insert({...data,company_id:companyId}).select("id").single();if(r.error)throw r.error;await qc.invalidateQueries();toast.success("Loja salva");}}/>}</>;
}