import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { useMe, brl, errMsg } from "@/lib/session";
import type { Database } from "@/integrations/supabase/types";
import { PageHeader, Loading, ErrorState, Empty } from "./states";
import { CompanyScope, RecordForm, type Field } from "./core";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Link } from "@tanstack/react-router";

type Job = Database["public"]["Tables"]["jobs"]["Row"];
export function JobsManager() { return <CompanyScope>{c => <Jobs companyId={c.id} />}</CompanyScope>; }
function Jobs({ companyId }: { companyId: string }) {
  const me = useMe(); const qc = useQueryClient(); const [editing, setEditing] = useState<Partial<Job> | null>(null); const [busy, setBusy] = useState(false);
  const q = useQuery({ queryKey: ["manage-jobs", companyId], queryFn: async () => { const r = await supabase.from("jobs").select("*, applications(id)").eq("company_id", companyId).order("created_at", { ascending: false }); if (r.error) throw r.error; return r.data; } });
  const stores = useQuery({ queryKey: ["stores", companyId], queryFn: async () => { const r = await supabase.from("stores").select("*").eq("company_id", companyId); if (r.error) throw r.error; return r.data; } });
  const fields: Field[] = [{ key: "title", label: "Cargo", required: true }, { key: "openings", label: "Quantidade de vagas", type: "number", min: 1, required: true }, { key: "description", label: "Descrição", type: "textarea", required: true }, { key: "requirements", label: "Requisitos", type: "textarea" }, { key: "salary", label: "Salário (R$)", type: "number", min: 0 }, { key: "benefits", label: "Benefícios" }, { key: "workload", label: "Jornada" }, { key: "schedule", label: "Escala" }, { key: "city", label: "Localização", required: true }, { key: "start_date", label: "Início previsto", type: "date" }, { key: "store_id", label: "Loja", options: (stores.data ?? []).map(s => ({ value: s.id, label: s.name })) }];
  async function status(id: string, status: Job["status"]) { setBusy(true); try { const r = await supabase.from("jobs").update({ status, ...(status === "publicada" ? { published_at: new Date().toISOString() } : {}) }).eq("id", id).select("id").single(); if (r.error) throw r.error; toast.success("Status atualizado"); await qc.invalidateQueries({ queryKey: ["manage-jobs"] }); } catch (e) { toast.error(errMsg(e)); } finally { setBusy(false); } }
  return <><PageHeader eyebrow="Trabalho fixo" title="Gestão de vagas" actions={<Button onClick={() => setEditing({ openings: 1 })}>Criar vaga</Button>} />{q.error || stores.error ? <ErrorState error={q.error || stores.error} retry={() => { q.refetch(); stores.refetch(); }} /> : q.isLoading ? <Loading /> : !q.data?.length ? <Empty title="Nenhuma vaga cadastrada" /> : <div className="space-y-3">{q.data.map(j => <article className="rounded-lg border bg-card p-5" key={j.id}><div className="flex flex-wrap justify-between gap-2"><h2 className="font-semibold">{j.title}</h2><Badge variant="muted">{j.status}</Badge></div><p className="my-2 whitespace-pre-wrap text-sm text-muted-foreground">{j.description}</p><p className="text-sm">{j.city} · {j.openings} vagas · {brl(j.salary)} · {j.applications.length} candidatos</p><div className="mt-4 flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => setEditing(j)}>Editar / visualizar</Button><Button size="sm" variant="outline" asChild><Link to="/app/empresa/recrutamento" search={{ vaga: j.id }}>Candidatos</Link></Button>{j.status !== "publicada" && <Button size="sm" disabled={busy} onClick={() => status(j.id, "publicada")}>Publicar</Button>}{j.status === "publicada" && <Button size="sm" variant="outline" disabled={busy} onClick={() => status(j.id, "pausada")}>Pausar</Button>}{j.status !== "encerrada" && <Button size="sm" variant="outline" disabled={busy} onClick={() => status(j.id, "encerrada")}>Encerrar</Button>}</div></article>)}</div>}
  {editing && <RecordForm title={editing.id ? "Editar vaga" : "Criar rascunho"} initial={editing} fields={fields} onClose={() => setEditing(null)} onSave={async v => { if (!me.data) throw Error("Sessão indisponível"); if (v.title.trim().length < 3 || Number(v.openings) < 1 || !Number.isInteger(Number(v.openings))) throw Error("Informe cargo e quantidade válida"); const data = { title: v.title.trim(), description: v.description, requirements: v.requirements, salary: v.salary ? Number(v.salary) : null, benefits: v.benefits, workload: v.workload, schedule: v.schedule, city: v.city, start_date: v.start_date || null, openings: Number(v.openings), store_id: v.store_id || null }; const r = editing.id ? await supabase.from("jobs").update(data).eq("id", editing.id).select("id").single() : await supabase.from("jobs").insert({ ...data, company_id: companyId, created_by: me.data.user.id, status: "rascunho", published_at: null }).select("id").single(); if (r.error) throw r.error; toast.success("Vaga salva"); await qc.invalidateQueries(); }} />}</>;
}