import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { useMe, fmtDateTime, errMsg } from "@/lib/session";
import { STAGE_LABEL } from "@/lib/labels";
import { CompanyScope, RecordForm, type Field } from "./core";
import { PageHeader, Empty, Loading, ErrorState } from "./states";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import type { Database } from "@/integrations/supabase/types";

export function Recruitment({ jobId }: { jobId?: string }) { return <CompanyScope>{c => <Candidates companyId={c.id} jobId={jobId} />}</CompanyScope>; }
function Candidates({ companyId, jobId }: { companyId: string; jobId?: string }) {
  const qc = useQueryClient(); const [selected, setSelected] = useState("");
  const q = useQuery({ queryKey: ["recruitment", companyId, jobId], queryFn: async () => { let query = supabase.from("applications").select("*, jobs!inner(title,company_id), professionals(full_name,headline)").eq("jobs.company_id", companyId); if (jobId) query = query.eq("job_id", jobId); const r = await query.order("created_at"); if (r.error) throw r.error; return r.data; } });
  const [busy, setBusy] = useState(false);
  async function stage(id: string, stage: Database["public"]["Enums"]["application_stage"]) { setBusy(true); try { const r = await supabase.from("applications").update({ stage }).eq("id", id).select("id").single(); if (r.error) throw r.error; toast.success("Etapa atualizada e profissional notificado"); await qc.invalidateQueries(); } catch (e) { toast.error(errMsg(e)); } finally { setBusy(false); } }
  return <><PageHeader title="Recrutamento" eyebrow="Trabalho fixo" />{q.error ? <ErrorState error={q.error} retry={() => q.refetch()} /> : q.isLoading ? <Loading /> : !q.data?.length ? <Empty title="Nenhuma candidatura" /> : <div className="space-y-3">{q.data.map(a => <article key={a.id} className="rounded-lg border bg-card p-5"><div className="flex flex-wrap justify-between gap-2"><div><h2 className="font-semibold">{a.professionals?.full_name}</h2><p className="text-sm text-muted-foreground">{a.jobs.title} · {a.professionals?.headline}</p></div><Badge variant="muted">{STAGE_LABEL[a.stage]}</Badge></div><p className="mt-2 text-xs text-muted-foreground">Candidatura: {fmtDateTime(a.created_at)} · Primeiro contato: {fmtDateTime(a.first_contact_at)} · Contratação: {fmtDateTime(a.hired_at)}</p>{!a.first_contact_at && new Date(a.created_at).toDateString() !== new Date().toDateString() && <p className="mt-1 text-sm text-destructive">SLA D+0 em risco — primeiro contato pendente</p>}<div className="mt-3 flex flex-wrap items-center gap-2"><select aria-label={`Etapa de ${a.professionals?.full_name}`} className="h-10 max-w-full rounded-md border bg-card px-3 text-sm" value={a.stage} disabled={busy} onChange={e => stage(a.id, e.target.value as Database["public"]["Enums"]["application_stage"])}>{Object.entries(STAGE_LABEL).map(([v,l]) => <option key={v} value={v}>{l}</option>)}</select><Button variant="outline" size="sm" onClick={() => setSelected(selected === a.id ? "" : a.id)}>Contatos, entrevista e histórico</Button></div>{selected === a.id && <CandidateDetails id={a.id} notes={a.notes} />}</article>)}</div>}</>;
}

function CandidateDetails({ id, notes }: { id: string; notes: string | null }) {
  const me = useMe(); const qc = useQueryClient(); const [mode, setMode] = useState<"contact" | "interview" | "note" | null>(null);
  const [interviewId, setInterviewId] = useState(""); const [initial, setInitial] = useState<Record<string, unknown>>({});
  const q = useQuery({ queryKey: ["candidate-details", id], queryFn: async () => { const [h,i] = await Promise.all([supabase.from("recruitment_history").select("*").eq("application_id",id).order("created_at",{ascending:false}), supabase.from("interviews").select("*").eq("application_id",id).order("scheduled_at")]); if(h.error) throw h.error; if(i.error) throw i.error; return {history:h.data, interviews:i.data}; } });
  const fields: Field[] = mode === "contact" ? [{key:"channel",label:"Canal",required:true,options:["Telefone","WhatsApp","Email","Presencial"].map(v=>({value:v,label:v}))},{key:"result",label:"Resultado",required:true},{key:"next_contact_at",label:"Próximo contato",type:"datetime-local"},{key:"note",label:"Observação / responsável",type:"textarea"}] : mode === "note" ? [{key:"notes",label:"Observações",type:"textarea",required:true}] : [{key:"scheduled_at",label:"Data e hora",type:"datetime-local",required:true},{key:"location",label:"Local / link",required:true},{key:"interviewer",label:"Responsável",required:true},{key:"status",label:"Status",options:["agendada","realizada","reagendada","faltou","cancelada"].map(v=>({value:v,label:v}))},{key:"result",label:"Resultado",options:["pendente","aprovado","reprovado"].map(v=>({value:v,label:v}))},{key:"notes",label:"Observações",type:"textarea"}];
  async function save(v: Record<string,string>) {
    if(!me.data) throw Error("Sessão indisponível");
    if(mode === "contact") { const r=await supabase.from("recruitment_history").insert({application_id:id,kind:"contato",actor_id:me.data.user.id,channel:(v["channel"] ?? ""),result:(v["result"] ?? ""),note:(v["note"] ?? ""),next_contact_at:(v["next_contact_at"] ?? "")?new Date((v["next_contact_at"] ?? "")).toISOString():null}); if(r.error)throw r.error; const u=await supabase.from("applications").update({stage:"contato",first_contact_at:new Date().toISOString()}).eq("id",id).select("id").single();if(u.error)throw u.error; }
    else if(mode === "note") { const r=await supabase.from("applications").update({notes:(v["notes"] ?? "")}).eq("id",id).select("id").single();if(r.error)throw r.error;const h=await supabase.from("recruitment_history").insert({application_id:id,kind:"nota",note:(v["notes"] ?? ""),actor_id:me.data.user.id});if(h.error)throw h.error; }
    else {const payload={application_id:id,scheduled_at:new Date((v["scheduled_at"] ?? "")).toISOString(),location:(v["location"] ?? ""),interviewer:(v["interviewer"] ?? ""),status:(v["status"] ?? "")||"agendada",result:(v["result"] ?? "")||"pendente",notes:(v["notes"] ?? ""),created_by:me.data.user.id};const r=interviewId?await supabase.from("interviews").update(payload).eq("id",interviewId).select("id").single():await supabase.from("interviews").insert(payload).select("id").single();if(r.error)throw r.error;const u=await supabase.from("applications").update({stage:"entrevista",interview_at:payload.scheduled_at}).eq("id",id).select("id").single();if(u.error)throw u.error; }
    toast.success("Registro salvo"); await qc.invalidateQueries();
  }
  return <div className="mt-4 space-y-3 border-t pt-4"><div className="flex flex-wrap gap-2"><Button size="sm" onClick={()=>{setInitial({});setMode("contact");}}>Registrar contato / segundo contato</Button><Button variant="outline" size="sm" onClick={()=>{setInitial({status:"agendada",result:"pendente"});setInterviewId("");setMode("interview");}}>Agendar entrevista</Button><Button variant="outline" size="sm" onClick={()=>{setInitial({notes});setMode("note");}}>Observações</Button></div>{notes&&<p className="whitespace-pre-wrap text-sm">{notes}</p>}{q.error?<ErrorState error={q.error}/>:q.isLoading?<Loading/>:<><h3 className="font-semibold text-sm">Entrevistas</h3>{q.data?.interviews.map(i=><div key={i.id} className="flex flex-wrap items-center justify-between gap-2 text-sm"><span>{fmtDateTime(i.scheduled_at)} · {i.status} · {i.result} · {i.interviewer}</span><Button size="sm" variant="outline" onClick={()=>{setInitial({...i,scheduled_at:i.scheduled_at.slice(0,16)});setInterviewId(i.id);setMode("interview");}}>Resultado / reagendar</Button></div>)}<h3 className="text-sm font-semibold">Histórico</h3>{q.data?.history.map(h=><p key={h.id} className="text-xs text-muted-foreground">{fmtDateTime(h.created_at)} · {h.kind} · {h.to_stage?STAGE_LABEL[h.to_stage]:h.channel} · {h.result||h.note}{h.next_contact_at?` · Próximo: ${fmtDateTime(h.next_contact_at)}`:""}</p>)}</>}{mode&&<RecordForm title={mode==="contact"?"Registrar contato":mode==="note"?"Observações":"Entrevista"} initial={initial} fields={fields} onSave={save} onClose={()=>setMode(null)}/>}</div>;
}