import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { downloadCSV, fmtDateTime } from "@/lib/session";
import { CompanyScope } from "./core";
import { PageHeader, Empty, ErrorState, Loading, Stat } from "./states";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Download } from "lucide-react";

export function Reports(){return <CompanyScope>{c=><CompanyReports companyId={c.id}/>}</CompanyScope>;}
function CompanyReports({companyId}:{companyId:string}){const [kind,setKind]=useState("vagas");const [from,setFrom]=useState("");const [to,setTo]=useState("");const [text,setText]=useState("");const [status,setStatus]=useState("");const [store,setStore]=useState("");
const q=useQuery({queryKey:["reports",companyId],queryFn:async()=>{const [j,a,o,w,s]=await Promise.all([supabase.from("jobs").select("*").eq("company_id",companyId),supabase.from("applications").select("*, jobs!inner(title,company_id,store_id), professionals(full_name)").eq("jobs.company_id",companyId),supabase.from("freelance_opportunities").select("*").eq("company_id",companyId),supabase.from("freelance_assignments").select("*, professionals(full_name), freelance_opportunities(title,store_id,activity_type)").eq("company_id",companyId),supabase.from("stores").select("id,name").eq("company_id",companyId)]);for(const r of [j,a,o,w,s])if(r.error)throw r.error;return {jobs:j.data??[],apps:a.data??[],opps:o.data??[],work:w.data??[],stores:s.data??[]};}});
let rows:Record<string,unknown>[]=[];const d=q.data;if(d){if(kind==="vagas")rows=d.jobs.map(j=>({id:j.id,titulo:j.title,status:j.status,data:j.created_at,loja:j.store_id,quantidade:j.openings}));else if(["candidatos","recrutamento"].includes(kind))rows=d.apps.map(a=>({id:a.id,profissional:a.professionals?.full_name,vaga:a.jobs.title,status:a.stage,data:a.created_at,loja:a.jobs.store_id,primeiro_contato:a.first_contact_at,entrevista:a.interview_at,contratacao:a.hired_at}));else if(kind==="oportunidades")rows=d.opps.map(o=>({id:o.id,titulo:o.title,status:o.status,data:o.starts_at,loja:o.store_id,valor:o.pay_amount,atividade:o.activity_type}));else rows=d.work.map(w=>({id:w.id,profissional:w.professionals?.full_name,oportunidade:w.freelance_opportunities?.title,status:w.status,data:w.starts_at,loja:w.freelance_opportunities?.store_id,checkin:w.checkin_at,checkout:w.checkout_at,executada:w.executed,resultado:w.execution_result,horas:w.checkin_at&&w.checkout_at?(new Date(w.checkout_at).getTime()-new Date(w.checkin_at).getTime())/3600000:null}));}
rows=rows.filter(r=>(!from||String(r["data"]).slice(0,10)>=from)&&(!to||String(r["data"]).slice(0,10)<=to)&&(!status||r["status"]===status)&&(!store||r["loja"]===store)&&(!text||Object.values(r).join(" ").toLowerCase().includes(text.toLowerCase())));const executed=rows.filter(r=>r["executada"]===true).length;const results=rows.filter(r=>typeof r["executada"]==="boolean").length;
return <><PageHeader title="Relatórios" actions={<Button disabled={!rows.length} onClick={()=>downloadCSV(`a-ponto-${kind}.csv`,rows)}><Download/>Exportar CSV</Button>}/><div className="mb-5 grid gap-3 sm:grid-cols-3"><div className="space-y-1"><Label htmlFor="report-kind">Relatório</Label><select id="report-kind" className="h-10 w-full rounded-md border bg-card px-3 text-sm" value={kind} onChange={e=>{setKind(e.target.value);setStatus("");}}>{["vagas","candidatos","recrutamento","freelancers","oportunidades","trabalhos realizados","produtividade","execução"].map(k=><option key={k} value={k}>{k}</option>)}</select></div><div className="space-y-1"><Label htmlFor="report-from">De</Label><Input id="report-from" type="date" value={from} onChange={e=>setFrom(e.target.value)}/></div><div className="space-y-1"><Label htmlFor="report-to">Até</Label><Input id="report-to" type="date" value={to} onChange={e=>setTo(e.target.value)}/></div><Input aria-label="Filtrar relatório" placeholder="Profissional, vaga ou oportunidade" value={text} onChange={e=>setText(e.target.value)}/><select aria-label="Status do relatório" className="h-10 rounded-md border bg-card px-3 text-sm" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos status</option>{Array.from(new Set(rows.map(r=>String(r["status"])))).map(s=><option key={s} value={s}>{s}</option>)}</select><select aria-label="Loja do relatório" className="h-10 rounded-md border bg-card px-3 text-sm" value={store} onChange={e=>setStore(e.target.value)}><option value="">Todas lojas</option>{d?.stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div>{q.error?<ErrorState error={q.error} retry={()=>q.refetch()}/>:q.isLoading?<Loading/>:<><div className="mb-5 grid grid-cols-2 gap-3"><Stat label="Registros" value={rows.length}/><Stat label="Execução" value={results?`${Math.round(executed/results*100)}%`:"—"}/></div>{!rows.length?<Empty title="Nenhum registro no período"/>:<div className="overflow-x-auto rounded-lg border bg-card"><table className="w-full text-left text-sm"><thead className="bg-muted"><tr><th className="p-3">Nome / título</th><th className="p-3">Status</th><th className="p-3">Data</th><th className="p-3">Execução</th></tr></thead><tbody>{rows.map(r=><tr className="border-t" key={String(r["id"])}><td className="p-3">{String(r["profissional"]??r["titulo"]??"—")}<p className="text-xs text-muted-foreground">{String(r["vaga"]??r["oportunidade"]??"")}</p></td><td className="p-3">{String(r["status"])}</td><td className="whitespace-nowrap p-3">{fmtDateTime(String(r["data"]))}</td><td className="p-3">{r["executada"]===true?"Executada":r["executada"]===false?"Não executada":"—"}</td></tr>)}</tbody></table></div>}</>}</>;
}