/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/app/route'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedAppCandidaturasRouteImport } from './routes/_authenticated/app/candidaturas'
import { Route as AuthenticatedAppCheckinRouteImport } from './routes/_authenticated/app/checkin'
import { Route as AuthenticatedAppGanhosRouteImport } from './routes/_authenticated/app/ganhos'
import { Route as AuthenticatedAppNotificacoesRouteImport } from './routes/_authenticated/app/notificacoes'
import { Route as AuthenticatedAppOportunidadesRouteImport } from './routes/_authenticated/app/oportunidades'
import { Route as AuthenticatedAppVagasRouteImport } from './routes/_authenticated/app/vagas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppCandidaturasRoute =
  AuthenticatedAppCandidaturasRouteImport.update({
    id: '/candidaturas',
    path: '/candidaturas',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppCheckinRoute = AuthenticatedAppCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppGanhosRoute = AuthenticatedAppGanhosRouteImport.update({
  id: '/ganhos',
  path: '/ganhos',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppNotificacoesRoute =
  AuthenticatedAppNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppOportunidadesRoute =
  AuthenticatedAppOportunidadesRouteImport.update({
    id: '/oportunidades',
    path: '/oportunidades',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppVagasRoute = AuthenticatedAppVagasRouteImport.update({
  id: '/vagas',
  path: '/vagas',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/app/candidaturas': typeof AuthenticatedAppCandidaturasRoute
  '/app/checkin': typeof AuthenticatedAppCheckinRoute
  '/app/ganhos': typeof AuthenticatedAppGanhosRoute
  '/app/notificacoes': typeof AuthenticatedAppNotificacoesRoute
  '/app/oportunidades': typeof AuthenticatedAppOportunidadesRoute
  '/app/vagas': typeof AuthenticatedAppVagasRoute
  '/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/candidaturas': typeof AuthenticatedAppCandidaturasRoute
  '/app/checkin': typeof AuthenticatedAppCheckinRoute
  '/app/ganhos': typeof AuthenticatedAppGanhosRoute
  '/app/notificacoes': typeof AuthenticatedAppNotificacoesRoute
  '/app/oportunidades': typeof AuthenticatedAppOportunidadesRoute
  '/app/vagas': typeof AuthenticatedAppVagasRoute
  '/app': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/_authenticated/app/candidaturas': typeof AuthenticatedAppCandidaturasRoute
  '/_authenticated/app/checkin': typeof AuthenticatedAppCheckinRoute
  '/_authenticated/app/ganhos': typeof AuthenticatedAppGanhosRoute
  '/_authenticated/app/notificacoes': typeof AuthenticatedAppNotificacoesRoute
  '/_authenticated/app/oportunidades': typeof AuthenticatedAppOportunidadesRoute
  '/_authenticated/app/vagas': typeof AuthenticatedAppVagasRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacidade'
    | '/reset-password'
    | '/app'
    | '/app/candidaturas'
    | '/app/checkin'
    | '/app/ganhos'
    | '/app/notificacoes'
    | '/app/oportunidades'
    | '/app/vagas'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacidade'
    | '/reset-password'
    | '/app/candidaturas'
    | '/app/checkin'
    | '/app/ganhos'
    | '/app/notificacoes'
    | '/app/oportunidades'
    | '/app/vagas'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacidade'
    | '/reset-password'
    | '/_authenticated/app'
    | '/_authenticated/app/candidaturas'
    | '/_authenticated/app/checkin'
    | '/_authenticated/app/ganhos'
    | '/_authenticated/app/notificacoes'
    | '/_authenticated/app/oportunidades'
    | '/_authenticated/app/vagas'
    | '/_authenticated/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/candidaturas': {
      id: '/_authenticated/app/candidaturas'
      path: '/candidaturas'
      fullPath: '/app/candidaturas'
      preLoaderRoute: typeof AuthenticatedAppCandidaturasRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/checkin': {
      id: '/_authenticated/app/checkin'
      path: '/checkin'
      fullPath: '/app/checkin'
      preLoaderRoute: typeof AuthenticatedAppCheckinRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/ganhos': {
      id: '/_authenticated/app/ganhos'
      path: '/ganhos'
      fullPath: '/app/ganhos'
      preLoaderRoute: typeof AuthenticatedAppGanhosRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/notificacoes': {
      id: '/_authenticated/app/notificacoes'
      path: '/notificacoes'
      fullPath: '/app/notificacoes'
      preLoaderRoute: typeof AuthenticatedAppNotificacoesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/oportunidades': {
      id: '/_authenticated/app/oportunidades'
      path: '/oportunidades'
      fullPath: '/app/oportunidades'
      preLoaderRoute: typeof AuthenticatedAppOportunidadesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/vagas': {
      id: '/_authenticated/app/vagas'
      path: '/vagas'
      fullPath: '/app/vagas'
      preLoaderRoute: typeof AuthenticatedAppVagasRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
  }
}

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppCandidaturasRoute: typeof AuthenticatedAppCandidaturasRoute
  AuthenticatedAppCheckinRoute: typeof AuthenticatedAppCheckinRoute
  AuthenticatedAppGanhosRoute: typeof AuthenticatedAppGanhosRoute
  AuthenticatedAppNotificacoesRoute: typeof AuthenticatedAppNotificacoesRoute
  AuthenticatedAppOportunidadesRoute: typeof AuthenticatedAppOportunidadesRoute
  AuthenticatedAppVagasRoute: typeof AuthenticatedAppVagasRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppCandidaturasRoute: AuthenticatedAppCandidaturasRoute,
  AuthenticatedAppCheckinRoute: AuthenticatedAppCheckinRoute,
  AuthenticatedAppGanhosRoute: AuthenticatedAppGanhosRoute,
  AuthenticatedAppNotificacoesRoute: AuthenticatedAppNotificacoesRoute,
  AuthenticatedAppOportunidadesRoute: AuthenticatedAppOportunidadesRoute,
  AuthenticatedAppVagasRoute: AuthenticatedAppVagasRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
